AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cartrack CloudFormation template

Resources:
  Cartrack-VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "172.19.0.0/16"
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: "Cartrack-VPC"

  Cartrack-SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Cartrack SG"
      VpcId: !Ref Cartrack-VPC
      Tags:
        - Key: Name
          Value: "Cartrack-SG"

  Cartrack-Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref Cartrack-VPC
      CidrBlock: "172.19.0.0/24"

  #  The main server instance
  Cartrack-ec2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0f9c9d7f"
      InstanceType: "t2.micro"
      KeyName: "Cartrack"
      SecurityGroups:
        - Ref: "Cartrack-SG"
      SubnetId:
        Ref: "Cartrack-Subnet"
      Tags:
        - Key: Name
          Value: "Cartrack-ec2"

  # DynamoDB tables
  # todo: modify the table structure
  # requires email username password(hashed)
  # user_device, access token and shared device to be populated by code
  Cartrack-DynamoDB-Users:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Cartrack-DynamoDB-Users
      Tags:
        - Key: Name
          Value: "Cartrack-DynamoDB-Users"

  # devices Table
  # requires device_id, device_name, device_color
  Cartrack-DynamoDB-Devices:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Cartrack-DynamoDB-Devices
      Tags:
        - Key: Name
          Value: "Cartrack-DynamoDB-Devices"

  # device location table
  # requires device_id lat long timestamp heading?
  Cartrack-DynamoDB-Locations:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Cartrack-DynamoDB-Locations
      Tags:
        - Key: Name
          Value: "Cartrack-DynamoDB-Locations"
