AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cartrack CloudFormation template

  This template creates a Cartrack instance.
Resources:
#  Cartrack:
#    Type: "AWS::EC2::VPC"
#    Properties:
#      CidrBlock: "172.16.0.1/24"
#      Tags:
#        - Key: Name
#          Value: "Cartrack"
#        - Key: cie21
#          Value: "Group1"

#  CartrackInternetGateway:
#    Type: "AWS::EC2::InternetGateway"
#
#  CartrackVPCGateway:
#    Type: AWS::EC2::VPCGatewayAttachment
#    Properties:
#      InternetGatewayId: !Ref CartrackInternetGateway
#      VpcId: !Ref Cartrack

  CarTrackSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: CarTrack SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  CarTrackEC2:
    Type: AWS::EC2::Instance
    Properties:
      # change to singapore
      AvailabilityZone: us-east-1a
      ImageId: ami-01cc34ab2709337aa
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref CarTrackSG
      UserData:
        !Base64 |
        #!/bin/bash
        yum update && yum upgrade -y
        yum install -y git
        git clone https://github.com/maomaocake/Car-Tracking.git ~/Car-Tracking
        cd Car-Tracking/backend
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        export PYTHONPATH=~/Car-Tracking
        python3 app.py &
        deactivate
        cd ../cartrak
        curl -sL https://rpm.nodesource.com/setup_10.x | bash -
        yum install -y nodejs
        npm install
        npm run build
        npm install -g serve
        serve -s build -l 80
      Tags:
        - Key: Name
          Value: CarTrack
        - Key: Environment
          Value: Dev
        - Key: cie21
          Value: group1

  CarTrackDynamoDBUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: CarTrackUsers

  CarTrackDynamoDBDeviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: device_id
            AttributeType: S
        KeySchema:
          - AttributeName: device_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: CarTrackDevices

  CarTrackDynamoDBLocationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: device_id
          AttributeType: S
      KeySchema:
        - AttributeName: device_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: CarTrackLocations